### ISSUE TITLE
You cannot use the mekanism:atomic_disassembler or mekanism:configurator to properly drop items when breaking the mekanism_turrets:ultimate_laser_turret

### ISSUE THREAD

**Issue by oritong** [x3rdev/MekanismTurrets#11]
I’m sorry, my English isn’t very good, so I used Copilot for translation. Please watch the video. When using the configurator or atomic disassembler to break the ultimate laser turret, it doesn’t drop any items, while other laser turrets drop items normally
[the video](https://www.bilibili.com/video/BV1pQ8SejEtV/)
Because the video was too large, I used Bilibili. Sorry, I don’t have a YouTube account.

**Comment by x3rdev** [comment]
Hi, just to confirm this is in 1.21 or 1.20.1?

**Comment by oritong** [comment]
> Hi, just to confirm this is in 1.21 or 1.20.1?

In version 1.20.1, items do not drop. As for version 1.21, I cannot load this mod properly, like issue#10.

**Comment by x3rdev** [comment]
Fixed in 1.1.6/2.0.5
