### ISSUE TITLE
Cant join server with mekanism turrets

### ISSUE THREAD

**Issue by Xplodin** [x3rdev/MekanismTurrets#12]
[software.bernie.geckolib.GeckoLib/]: Attempting to set animation data for BlockEntity too early! Must wait until after the BlockEntity has been set in the world. (class com.github.x3r.mekanism_turrets.common.block_entity.LaserTurretBlockEntity)

this error prevents people from joining the server. something with this and geckolib.
Removing mek turrets lets people back in.
It worked fine for a few days then recently had this issue

![image](https://github.com/user-attachments/assets/666f363b-165f-47a1-b9c8-778c83840879)

[com.connectivity.Connectivity/]: Network error for:packet_handler
java.lang.NullPointerException: Cannot invoke "software.bernie.geckolib.network.SerializableDataTicket.decode(net.minecraft.network.FriendlyByteBuf)" because "dataTicket" is null
    at software.bernie.geckolib.network.packet.BlockEntityAnimDataSyncPacket.decode(BlockEntityAnimDataSyncPacket.java:38) ~[geckolib-forge-1.20.1-4.4.7.jar%231007!/:4.4.7]
    at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:107) ~[forge-1.20.1-47.2.19-universal.jar%231361!/:?]
    at java.util.Optional.map(Optional.java:260) ~[?:?]

**Comment by x3rdev** [comment]
Hi, what version of mekanism turrets is this affecting? Are you on the latest version.

**Comment by Xplodin** [comment]
The latest on curseforge.  1.1.7

**Comment by x3rdev** [comment]
Ok perfect wait I just noticed that the error you sent at the bottom is extremely helpful. Im working on a fix for this and a new version should be available in a few hours.

**Comment by x3rdev** [comment]
fixed
