### ISSUE TITLE
Turret AI Server Crash

### ISSUE THREAD

**Issue by ZeroTronix** [x3rdev/MekanismTurrets#13]
We use the Turret mod for quite a while now but after today we cant join the server anymore because the turret ai ist constantly searching for an target that lag the compleate server until it crash.
![image](https://github.com/user-attachments/assets/02dcc3a2-e92e-4544-b2ad-6185ae8de413)
![image](https://github.com/user-attachments/assets/939204db-8fbf-4500-8abf-7e4939aad4b5)
Mod Version 1.1.8

**Comment by ZeroTronix** [comment]
after removing the mod and then start the server without to remove the turret worked. But it is still weird for week it worked and suddenly they cause problems. I had 8 Turrets

**Comment by x3rdev** [comment]
Hi, thanks so much for posting this issue, I will address this right away. But, I do want to ask some questions about your setup. Did you happen to modify any of the range settings for the turrets? Im assuming you were using a few ultimate turrets right?

**Comment by ZeroTronix** [comment]
I did not change any settings from the mod. I had a total of 8 turrets on the server.

**Comment by x3rdev** [comment]
Ok, thanks, I'll let you know if there's anything else

**Comment by x3rdev** [comment]
fixed in newest update
