### ISSUE TITLE
Turrets target cameramen from Stevedi Toilet mod

### ISSUE THREAD

**Issue by darthvader45** [x3rdev/MekanismTurrets#14]
The cameraman mob from the Stevedi Toilet mod (yes, it's a skibidi toilet mod, don't ask) seems to be considered a hostile mob for some reason, despite its code listing it as an animal (tamableanimal to be specific).  Any idea if those entities can be specifically blacklisted as targets, or if a filter system can be set up to choose which mobs get targeted and which do not?

**Comment by x3rdev** [comment]
The config has an option for this, but also this is the other mod's fault. The system for determining hostile mobs is the same as in vanilla.

**Comment by darthvader45** [comment]
Thanks, will use the config.
