### ISSUE TITLE
Visual Glitch with hotbar when turret is in it

### ISSUE THREAD

**Issue by darthvader45** [x3rdev/MekanismTurrets#6]
Hotbar items become dark and somewhat transparent when a turret is in the hotbar, including the turret itself.

![image](https://github.com/x3rdev/MekanismTurrets/assets/2816420/1317d544-1c26-4512-975e-961a68ef08d6)

**Comment by x3rdev** [comment]
fixed

**Comment by darthvader45** [comment]
Thank you very much, checking out the newest release 1.1.8 to see the fix.

**Comment by darthvader45** [comment]
Fix works, thank you.
