### ISSUE TITLE
[Backport Request] -- 1.19.2

### ISSUE THREAD

**Issue by weirdspecter** [x3rdev/MekanismTurrets#7]
Hi there.

Mekanism Turrets seems incredibly well suited for my modded game, but is unfortunately only available for 1.20.1. While I recognise that the time and effort involved in porting a mod across versions of Minecraft (and likely Forge) is substantial, I'd like to request that this mod be backported to 1.19.2.

Thank you for any and all consideration.

**Comment by KingSkel** [comment]
Unfortunately, there is not enough demand for anything pre1.20 so we will not pursue the task of backporting.

**Comment by weirdspecter** [comment]
That's disappointing to hear, but thank you for taking the time to get back to me.
